import {
  HeadContent,
  Outlet,
  Scripts,
  createRootRoute,
} from "@tanstack/react-router"
import type { ReactNode } from "react"
import { Provider } from "react-redux"

import DndProviderWrapper from "@/components/DndProviderWrapper"
import Layout from "@/components/Layout"
import store from "@/store/index"
import splitPaneCss from "../../styles/split-pane.css?url"

export const Route = createRootRoute({
  head: () => ({
    meta: [
      { title: "Talk CMS" },
      { charSet: "utf-8" },
      {
        name: "description",
        content: "Generated by create next app",
      },
      {
        name: "viewport",
        content: "width=device-width, initial-scale=1",
      },
    ],
    links: [
      { rel: "stylesheet", href: splitPaneCss },
      { rel: "icon", href: "/favicon.ico" },
    ],
  }),
  component: RootComponent,
})

function RootComponent() {
  return (
    <RootDocument>
      <Outlet />
    </RootDocument>
  )
}

function RootDocument({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <HeadContent />
      </head>
      <body>
        <Provider store={store}>
          <Layout>
            <DndProviderWrapper>{children}</DndProviderWrapper>
          </Layout>
        </Provider>
        <Scripts />
      </body>
    </html>
  )
}
