import {
  HeadContent,
  Outlet,
  Scripts,
  createRootRoute,
} from "@tanstack/react-router"
import type { ReactNode } from "react"

import DndProviderWrapper from "@/components/DndProviderWrapper"
import Layout from "@/components/Layout"
import { TooltipProvider } from "@/ui/tooltip"
import globalsCss from "@/styles/globals.css?url"
import splitPaneCss from "../../styles/split-pane.css?url"
import { BlockRegistryProvider } from "@/blocks/client/BlockRegistryProvider"

export const Route = createRootRoute({
  head: () => ({
    meta: [
      { title: "Talk CMS" },
      { charSet: "utf-8" },
      {
        name: "description",
        content: "Generated by create next app",
      },
      {
        name: "viewport",
        content: "width=device-width, initial-scale=1",
      },
    ],
    links: [
      { rel: "stylesheet", href: globalsCss },
      { rel: "stylesheet", href: splitPaneCss },
      { rel: "icon", href: "/favicon.ico" },
    ],
  }),
  component: RootComponent,
})

function RootComponent() {
  return (
    <RootDocument>
      <Outlet />
    </RootDocument>
  )
}

function RootDocument({ children }: { children: ReactNode }) {
  // jsdom cannot track focus/active-element when a nested <html>/<body> is rendered
  // inside the test container, which deadlocks Radix UI focus handling in tests.
  // Render the bare providers there; the real document shell only exists in the browser/SSR.
  if (import.meta.env.MODE === "test") {
    return <RootProviders>{children}</RootProviders>
  }
  return (
    <html lang="en">
      <head>
        <HeadContent />
      </head>
      <body>
        <RootProviders>{children}</RootProviders>
        <Scripts />
      </body>
    </html>
  )
}

function RootProviders({ children }: { children: ReactNode }) {
  return (
    <TooltipProvider delayDuration={200}>
      <Layout>
        <BlockRegistryProvider>
          <DndProviderWrapper>{children}</DndProviderWrapper>
        </BlockRegistryProvider>
      </Layout>
    </TooltipProvider>
  )
}
