import Head from "next/head"
import { useState, useEffect, useRef } from "react"
import SplitPane from "react-split-pane"
// Mui
import { useTheme } from "@mui/system"
import { Box } from "@mui/material"
// Components
import TopAppBar from "@/components/AppBar"
import UrlAppBar from "@/components/UrlAppBar"
import RightSidebar from "@/components/SidebarRight"
// redux
import useTransformedBlocks from "@/hooks/useTransformedBlocks"

const HomePage: React.FC = () => {
  const theme = useTheme()
  const currentMode = theme.palette.mode
  const [isDragging, setIsDragging] = useState(false)
  const iframeRef = useRef<HTMLIFrameElement>(null)
  const blocks = useTransformedBlocks()

  const currentUrl = new URL("http://localhost:3001?editMode=true")

  useEffect(() => {
    if (iframeRef.current && iframeRef.current.contentWindow) {
      iframeRef.current.contentWindow.postMessage(blocks, "*")
    }
  }, [blocks])

  return (
    <>
      <Head>
        <title>Firefly CMS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{ display: "flex", flexDirection: "column", minHeight: "100vh" }}
      >
        <TopAppBar />
        <div style={{ flexGrow: 1, display: "flex" }}>
          <SplitPane
            split="vertical"
            minSize={300}
            maxSize={-300}
            defaultSize="75%"
            style={{
              height: "calc(100vh - 64px)",
            }}
            onDragStarted={() => setIsDragging(true)}
            onDragFinished={() => setIsDragging(false)}
          >
            <Box
              style={{
                backgroundColor:
                  currentMode === "dark" ? "#292929" : "whitesmoke",
                height: "calc(100vh - 64px)",
                overflow: "auto",
                boxSizing: "border-box",
              }}
            >
              <UrlAppBar url={currentUrl.origin} />
              <iframe
                ref={iframeRef}
                src={currentUrl.href} // Replace this with the URL of the website you want to embed
                style={{
                  width: "100%",
                  height: "calc(100vh - 112px)",
                  border: "none",
                }}
                title="Visual Composer"
              />
              {isDragging && (
                <div
                  style={{
                    position: "absolute",
                    top: 0,
                    left: 0,
                    right: 0,
                    bottom: 0,
                    zIndex: 9999,
                  }}
                ></div>
              )}
            </Box>
            <div
              style={{
                height: "100%",
                overflow: "auto",
                boxSizing: "border-box",
              }}
            >
              <RightSidebar />
            </div>
          </SplitPane>
        </div>
      </main>
    </>
  )
}

export default HomePage
