import Head from "next/head"
import Image from "next/image"
import { useTheme } from "@mui/system"
const HomePage: React.FC = () => {
  const theme = useTheme()
  const currentMode = theme.palette.mode
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{ display: "flex", flexDirection: "column", minHeight: "100vh" }}
      >
      </main>
    </>
  )
}

export default HomePage
