import Head from "next/head"
import Image from "next/image"
import SplitPane from "react-split-pane"
import TopAppBar from "@/src/components/AppBar"
import RightSidebar from "@/src/components/SidebarRight"
import { useTheme } from "@mui/system"

const HomePage: React.FC = () => {
  const theme = useTheme()
  const currentMode = theme.palette.mode

  return (
    <>
      <Head>
        <title>Firefly CMS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{ display: "flex", flexDirection: "column", minHeight: "100vh" }}
      >
        <TopAppBar />
        <div style={{ flexGrow: 1, display: "flex" }}>
          <SplitPane
            split="vertical"
            minSize={300}
            maxSize={-300}
            defaultSize="75%"
            style={{
              height: "calc(100vh - 64px)",
            }}
          >
            <div
              style={{
                backgroundColor:
                  currentMode === "dark" ? "#292929" : "whitesmoke",
                height: "100%",
                overflow: "auto",
                boxSizing: "border-box",
              }}
            >
              {/* Visual Composer Area */}
            </div>
            <div
              style={{
                height: "100%",
                overflow: "auto",
                boxSizing: "border-box",
              }}
            >
              <RightSidebar />
            </div>
          </SplitPane>
        </div>
      </main>
    </>
  )
}

export default HomePage
