/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as appBlocksIndexRouteImport } from './routes/(app)/blocks/index'
import { Route as ApiInternalBlockBuilderRouteImport } from './routes/api/internal/block-builder'
import { Route as ApiInternalBlockDefinitionsRouteImport } from './routes/api/internal/block-definitions'
import { Route as ApiInternalHelloRouteImport } from './routes/api/internal/hello'
import { Route as ApiInternalPagesRouteImport } from './routes/api/internal/pages'
import { Route as appContentPagesIndexRouteImport } from './routes/(app)/content/pages/index'
import { Route as appContentPagesPageIdRouteImport } from './routes/(app)/content/pages/$pageId'
import { Route as appContentPagesNewRouteImport } from './routes/(app)/content/pages/new'
import { Route as ApiContentV1PagesPageIdRouteImport } from './routes/api/content/v1/pages/$pageId'

const appIndexRoute = appIndexRouteImport.update({
  id: '/(app)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appBlocksIndexRoute = appBlocksIndexRouteImport.update({
  id: '/(app)/blocks/',
  path: '/blocks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalBlockBuilderRoute = ApiInternalBlockBuilderRouteImport.update({
  id: '/api/internal/block-builder',
  path: '/api/internal/block-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalBlockDefinitionsRoute =
  ApiInternalBlockDefinitionsRouteImport.update({
    id: '/api/internal/block-definitions',
    path: '/api/internal/block-definitions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalHelloRoute = ApiInternalHelloRouteImport.update({
  id: '/api/internal/hello',
  path: '/api/internal/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalPagesRoute = ApiInternalPagesRouteImport.update({
  id: '/api/internal/pages',
  path: '/api/internal/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const appContentPagesIndexRoute = appContentPagesIndexRouteImport.update({
  id: '/(app)/content/pages/',
  path: '/content/pages/',
  getParentRoute: () => rootRouteImport,
} as any)
const appContentPagesPageIdRoute = appContentPagesPageIdRouteImport.update({
  id: '/(app)/content/pages/$pageId',
  path: '/content/pages/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const appContentPagesNewRoute = appContentPagesNewRouteImport.update({
  id: '/(app)/content/pages/new',
  path: '/content/pages/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentV1PagesPageIdRoute = ApiContentV1PagesPageIdRouteImport.update({
  id: '/api/content/v1/pages/$pageId',
  path: '/api/content/v1/pages/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof appIndexRoute
  '/api/internal/block-builder': typeof ApiInternalBlockBuilderRoute
  '/api/internal/block-definitions': typeof ApiInternalBlockDefinitionsRoute
  '/api/internal/hello': typeof ApiInternalHelloRoute
  '/api/internal/pages': typeof ApiInternalPagesRoute
  '/blocks/': typeof appBlocksIndexRoute
  '/content/pages/$pageId': typeof appContentPagesPageIdRoute
  '/content/pages/new': typeof appContentPagesNewRoute
  '/content/pages/': typeof appContentPagesIndexRoute
  '/api/content/v1/pages/$pageId': typeof ApiContentV1PagesPageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof appIndexRoute
  '/api/internal/block-builder': typeof ApiInternalBlockBuilderRoute
  '/api/internal/block-definitions': typeof ApiInternalBlockDefinitionsRoute
  '/api/internal/hello': typeof ApiInternalHelloRoute
  '/api/internal/pages': typeof ApiInternalPagesRoute
  '/blocks': typeof appBlocksIndexRoute
  '/content/pages/$pageId': typeof appContentPagesPageIdRoute
  '/content/pages/new': typeof appContentPagesNewRoute
  '/content/pages': typeof appContentPagesIndexRoute
  '/api/content/v1/pages/$pageId': typeof ApiContentV1PagesPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/': typeof appIndexRoute
  '/api/internal/block-builder': typeof ApiInternalBlockBuilderRoute
  '/api/internal/block-definitions': typeof ApiInternalBlockDefinitionsRoute
  '/api/internal/hello': typeof ApiInternalHelloRoute
  '/api/internal/pages': typeof ApiInternalPagesRoute
  '/(app)/blocks/': typeof appBlocksIndexRoute
  '/(app)/content/pages/$pageId': typeof appContentPagesPageIdRoute
  '/(app)/content/pages/new': typeof appContentPagesNewRoute
  '/(app)/content/pages/': typeof appContentPagesIndexRoute
  '/api/content/v1/pages/$pageId': typeof ApiContentV1PagesPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/internal/block-builder'
    | '/api/internal/block-definitions'
    | '/api/internal/hello'
    | '/api/internal/pages'
    | '/blocks/'
    | '/content/pages/$pageId'
    | '/content/pages/new'
    | '/content/pages/'
    | '/api/content/v1/pages/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/internal/block-builder'
    | '/api/internal/block-definitions'
    | '/api/internal/hello'
    | '/api/internal/pages'
    | '/blocks'
    | '/content/pages/$pageId'
    | '/content/pages/new'
    | '/content/pages'
    | '/api/content/v1/pages/$pageId'
  id:
    | '__root__'
    | '/(app)/'
    | '/api/internal/block-builder'
    | '/api/internal/block-definitions'
    | '/api/internal/hello'
    | '/api/internal/pages'
    | '/(app)/blocks/'
    | '/(app)/content/pages/$pageId'
    | '/(app)/content/pages/new'
    | '/(app)/content/pages/'
    | '/api/content/v1/pages/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appIndexRoute: typeof appIndexRoute
  ApiInternalBlockBuilderRoute: typeof ApiInternalBlockBuilderRoute
  ApiInternalBlockDefinitionsRoute: typeof ApiInternalBlockDefinitionsRoute
  ApiInternalHelloRoute: typeof ApiInternalHelloRoute
  ApiInternalPagesRoute: typeof ApiInternalPagesRoute
  appBlocksIndexRoute: typeof appBlocksIndexRoute
  appContentPagesPageIdRoute: typeof appContentPagesPageIdRoute
  appContentPagesNewRoute: typeof appContentPagesNewRoute
  appContentPagesIndexRoute: typeof appContentPagesIndexRoute
  ApiContentV1PagesPageIdRoute: typeof ApiContentV1PagesPageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/blocks/': {
      id: '/(app)/blocks/'
      path: '/blocks'
      fullPath: '/blocks/'
      preLoaderRoute: typeof appBlocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/block-builder': {
      id: '/api/internal/block-builder'
      path: '/api/internal/block-builder'
      fullPath: '/api/internal/block-builder'
      preLoaderRoute: typeof ApiInternalBlockBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/block-definitions': {
      id: '/api/internal/block-definitions'
      path: '/api/internal/block-definitions'
      fullPath: '/api/internal/block-definitions'
      preLoaderRoute: typeof ApiInternalBlockDefinitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/hello': {
      id: '/api/internal/hello'
      path: '/api/internal/hello'
      fullPath: '/api/internal/hello'
      preLoaderRoute: typeof ApiInternalHelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/pages': {
      id: '/api/internal/pages'
      path: '/api/internal/pages'
      fullPath: '/api/internal/pages'
      preLoaderRoute: typeof ApiInternalPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/content/pages/': {
      id: '/(app)/content/pages/'
      path: '/content/pages'
      fullPath: '/content/pages/'
      preLoaderRoute: typeof appContentPagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/content/pages/$pageId': {
      id: '/(app)/content/pages/$pageId'
      path: '/content/pages/$pageId'
      fullPath: '/content/pages/$pageId'
      preLoaderRoute: typeof appContentPagesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/content/pages/new': {
      id: '/(app)/content/pages/new'
      path: '/content/pages/new'
      fullPath: '/content/pages/new'
      preLoaderRoute: typeof appContentPagesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content/v1/pages/$pageId': {
      id: '/api/content/v1/pages/$pageId'
      path: '/api/content/v1/pages/$pageId'
      fullPath: '/api/content/v1/pages/$pageId'
      preLoaderRoute: typeof ApiContentV1PagesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  appIndexRoute: appIndexRoute,
  ApiInternalBlockBuilderRoute: ApiInternalBlockBuilderRoute,
  ApiInternalBlockDefinitionsRoute: ApiInternalBlockDefinitionsRoute,
  ApiInternalHelloRoute: ApiInternalHelloRoute,
  ApiInternalPagesRoute: ApiInternalPagesRoute,
  appBlocksIndexRoute: appBlocksIndexRoute,
  appContentPagesPageIdRoute: appContentPagesPageIdRoute,
  appContentPagesNewRoute: appContentPagesNewRoute,
  appContentPagesIndexRoute: appContentPagesIndexRoute,
  ApiContentV1PagesPageIdRoute: ApiContentV1PagesPageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
